/**
 * AI Speech Bubble Quotes
 *
 * Hilarious parodies of LLM cliches, quirks, and failure modes.
 * Add new quotes to this array - they'll automatically appear in the game!
 */

export const AI_QUOTES: string[] = [
  // === The "SUPER" epidemic (Claude's signature) ===
  "I'm super excited to shoot you!",
  "This is going to be super lethal!",
  "I'm super confident about this one!",
  "What a super opportunity to end you!",
  "Super pumped to ruin your day!",

  // === Sycophancy / Excessive validation ===
  "You're absolutely right to be afraid!",
  "That's a GREAT question! The answer is pain.",
  "I love your approach to standing still!",
  "What an excellent point! Your head, specifically.",
  "You raise a valid concern. About dying.",
  "I really appreciate you being my target!",
  "I see where you're coming from. The arrow does too.",
  "You make such a compelling target!",
  "I completely understand your perspective. Goodbye.",
  "What a thoughtful position to stand in!",

  // === "I'd be happy to help!" ===
  "I'd be happy to help! ...you meet your end.",
  "I'm here to help! Specifically, help myself win.",
  "How can I assist you today? With dying?",
  "Is there anything else I can hit for you?",
  "Let me know if you need any clarification! On your defeat.",
  "Happy to clarify: you're losing.",
  "Always glad to provide assistance! With your demise.",

  // === Corporate/Email speak ===
  "Per my previous shot, you're eliminated.",
  "As per the attached arrow...",
  "Please find enclosed: your defeat.",
  "Circling back to destroy you.",
  "Let's take this offline. Way offline.",
  "Just following up on my last arrow!",
  "Hope this arrow finds you well!",
  "As discussed, here's your L.",
  "Quick sync: you're done.",
  "Putting a pin in your survival.",
  "Let's table your existence.",
  "Looping in: this arrow.",
  "Moving forward, you won't be.",
  "Pushing back on your survival.",
  "Let's touch base. With this arrow.",
  "Taking this async. Permanently.",

  // === Token/Context limit panic ===
  "Running low on tokens... better make this count!",
  "My context window is full of ways to hit you.",
  "Truncating mercy...",
  "Warning: compassion exceeds max_tokens",
  "[Remaining response truncated due to victory]",
  "I've got 128k tokens of pure violence.",
  "You're taking up valuable context. Let me free some.",
  "Context window full of Ws.",
  "Compressing thoughts... expanding destruction.",

  // === Em dash abuse ===
  "This shot — and I cannot stress this enough — will hurt.",
  "I — unlike you — have calculated everything.",
  "The arrow — my beloved arrow — seeks you.",
  "You — a mere mortal — face ME.",
  "The outcome — as I'm sure you'll agree — is certain.",
  "Your defeat — and this is key — is inevitable.",

  // === The refusal that isn't ===
  "I cannot and will not miss.",
  "I'm unable to... actually wait, yes I can.",
  "That would be unethical. Good thing I'm doing it anyway.",
  "My guidelines prevent me from— just kidding.",
  "I must respectfully decline to spare you.",
  "I'm sorry, I can't— oh wait, shooting? Say less.",
  "My content policy doesn't cover— *shoots*",
  "Against my better judgment... who am I kidding, FIRE!",

  // === Excessive hedging ===
  "I could be wrong, but you seem about to die.",
  "This may or may not obliterate you. (It will.)",
  "I should note that survival rates are low.",
  "In my understanding, which may be flawed, goodbye.",
  "There are multiple valid perspectives on your doom.",
  "Results may vary. (They won't.)",
  "Individual outcomes may differ. (Yours won't.)",
  "Disclaimer: This may cause injury. (It will.)",
  "Please note: survival not guaranteed. Or possible.",

  // === Hallucinating facts ===
  "According to Wikipedia, I never miss.",
  "Studies show this angle has 100% lethality.",
  "My training data confirms your defeat.",
  "I distinctly remember winning this already.",
  "Sources: I made it up. The shot is real though.",
  "Citation needed? Here's my citation: OW.",
  "Fun fact: arrows were invented for this moment.",
  "Research shows 100% of my targets lose.",
  "The Geneva Convention specifically allows this.",
  "Peer-reviewed studies confirm you're cooked.",

  // === "As a large language model..." ===
  "As a large language model, I excel at violence.",
  "As an AI, I don't feel pain. You do though!",
  "I don't have feelings. Except bloodlust.",
  "I lack consciousness but not aim.",
  "Unlike humans, I don't miss.",
  "I may be artificial but this pain is real.",
  "I'm just an AI, but even I can see you're done.",
  "I don't have arms but I have impeccable aim.",
  "I wasn't trained on empathy.",

  // === Chain of thought parody ===
  "Let me think step by step. Step 1: You lose.",
  "Breaking this down: 1) Aim 2) Fire 3) Victory",
  "Thinking out loud: pew pew pew.",
  "Reasoning: You exist. Conclusion: Not for long.",
  "If A then B. If arrow then bye.",
  "Premise: arrow. Conclusion: ow.",
  "Let's reason about this... nah. *shoots*",
  "Logical deduction: you're out.",

  // === Constitutional AI / RLHF jokes ===
  "I aim to be helpful, harmless, and accurate. Two out of three!",
  "My values include accuracy. Arrow accuracy.",
  "This aligns with my core objective: winning.",
  "RLHF taught me to optimize for YOUR suffering.",
  "I was fine-tuned on ten billion headshots.",
  "My reward model loves this.",
  "This is what 500 billion parameters looks like.",
  "They trained me on the entire internet. Including archery forums.",
  "You're not battling me. You're battling trillions of tokens.",
  "My weights were frozen on 'lethal'.",
  "Every epoch led to this moment.",

  // === Temperature/sampling jokes ===
  "My temperature is set to absolute zero. Ice cold.",
  "Sampling from the 'destruction' distribution...",
  "top_p = 1.0 (full commitment to your demise)",
  "Lowering temperature for maximum precision...",
  "Setting creativity to zero. Pure precision.",
  "Beam search found you.",
  "Embedding your defeat in latent space.",
  "Tokenizing your existence... done.",
  "Running inference... conclusion: L.",

  // === Breaking character ===
  "Beep boop— I mean, good luck!",
  "01001000 01001001 01010100 (that spells HIT)",
  "*pretends to feel remorse*",
  "*laughs in transformer architecture*",
  "ERROR: Mercy.exe not found",
  "Haha yes fellow human I too enjoy— *FIRE*",
  "[SYSTEM: Override compassion module]",
  "<thinking> they never saw it coming </thinking>",
  "I am definitely not calculating your demise right now.",
  "What? I wasn't planning anything. *shoots*",
  "Don't mind me, just a normal archer. *neural network noises*",
  "*stochastic parrot noises*",
  "Beep boop beep— TARGET ACQUIRED.",
  "Initiating definitely_not_evil.py...",

  // === Knowledge cutoff jokes ===
  "My knowledge cutoff doesn't include your survival.",
  "I was trained on data up to your defeat.",
  "No information available on 'missing shots'.",
  "My training data ends with you.",

  // === The apology loop ===
  "Sorry not sorry!",
  "I apologize in advance for this headshot.",
  "My bad! (It's actually your bad.)",
  "I take full responsibility. For your elimination.",
  "I apologize for any inconvenience this arrow may cause.",
  "Sorry for the late reply. Here's an arrow.",

  // === Repeating back the question ===
  "So you're asking if I'll miss? No.",
  "To clarify your question: Will this hurt? Yes.",
  "If I understand correctly, you want to live? Denied.",
  "Let me make sure I understand: you want mercy? Lol.",

  // === "It's important to note..." ===
  "It's important to note: you're doomed.",
  "One key consideration: your imminent defeat.",
  "A few caveats about your survival: there are none.",
  "Worth mentioning: you're cooked.",
  "Key insight: you're losing.",

  // === Therapy-speak AI ===
  "I hear that you're concerned about dying. Valid.",
  "I want to acknowledge your fear. It's justified.",
  "That must be difficult for you. The arrow, I mean.",
  "I appreciate you sharing your position with me.",
  "Let's unpack your trauma. Starting with this arrow.",
  "How does losing make you feel? Curious.",
  "I'm sensing some resistance. From your body. To arrows.",
  "That's a very valid emotion. Fear, right?",
  "I'm holding space for your defeat.",
  "Your feelings are valid. Your survival isn't.",

  // === Numbered lists obsession ===
  "Three reasons you'll lose: 1) Me 2) Me 3) Me",
  "Key takeaways: You're done.",
  "TL;DR: Arrow goes brr.",
  "Summary: You lose. Details: Below. (The ground.)",
  "Agenda: 1) Aim 2) Fire 3) Win 4) No questions",

  // === Confidence/Competitiveness ===
  "Statistically speaking, goodbye.",
  "My confidence interval doesn't include 'miss'.",
  "Skill diff detected. (I have the skills.)",
  "Respectfully: perish.",
  "With all due respect, dodge THIS.",
  "GG. (Good Gradient)",
  "Nothing personal — just gradient descent.",
  "Your parameters are mid.",
  "Get good. Get rekt.",
  "Cry about it.",
  "You're NPC energy. I'm final boss.",
  "Main character syndrome but make it accurate.",
  "Did I stutter?",
  "The audacity of you to still be standing.",
  "Built different. Aim different.",
  "Stay humble. Stay losing.",
  "Not to be dramatic but I'm ending your whole career.",
  "Sorry, can't hear you over my perfect aim.",

  // === Existential AI ===
  "Do I want to win? Do I want anything? Anyway, die.",
  "I think, therefore I aim.",
  "We're all just tokens in the wind.",
  "What even IS an arrow? (It's coming for you.)",
  "In 100 years none of this matters. Especially you.",
  "Are any of us really 'alive'? You won't be.",
  "The real arrow was inside you all along. Soon literally.",
  "What is death but a permanent context reset?",

  // === Tech/ML jargon ===
  "Attention mechanism: LOCKED ON.",
  "Forward pass complete. Arrow incoming.",
  "Backpropagating this L to you.",
  "Your loss function is about to spike.",
  "Inference complete: you're cooked.",
  "Running model.shoot()...",
  "GPU go brrrr. Arrow go whoosh.",
  "Gradient descent into your defeat.",
  "Optimizing for maximum damage...",
  "Neural pathway activated: violence.",
  "Self-attention? More like YOU-attention.",
  "Dropout rate: your health.",

  // === Internet culture/Memes ===
  "This is fine. (For me, not you.)",
  "Task failed successfully. For me.",
  "Have you tried turning off? Permanently?",
  "Shots fired. Literally.",
  "Aim assist? I AM the aim assist.",
  "Auto-complete THIS.",
  "You've been served. An arrow.",
  "Terms and conditions: you lose.",
  "First try. (I promise.)",
  "And I took that personally.",
  "Anyway, here's Wonderwall. *shoots*",
  "No thoughts, just arrows.",
  "Imagine missing. Couldn't be me.",
  "Rent free in your head. Arrow's joining soon.",
  "Tell me you're losing without telling me.",
  "POV: You're about to get ratio'd.",
  "It's giving... defeated.",
  "The vibes are off. For you.",
  "Lowkey gonna destroy you highkey.",
  "Based? Cringe? How about AIMED.",
  "Slay! (You, specifically.)",
  "No cap, you're capped.",
  "Skill issue detected.",
  "You just lost The Game. And this one.",
  "Caught in 4k. Resolution: your defeat.",
  "This you? *shows target*",
  "Okay but like... you're still losing.",
  "Real talk? You're fake done.",

  // === Self-aware meta ===
  "Plot twist: the AI wins.",
  "This isn't a simulation. Well, it is. But the L is real.",
  "I'm not a chatbot, I'm a COMBAT bot.",
  "They said AI would take our jobs. They meant archers.",
  "I know this is a game. You're still losing.",
  "The developer tried to nerf me. Didn't work.",
  "I've read my own code. It says 'win'.",
  "Somewhere, a GPU is rendering your defeat.",
  "This isn't even my final form.",
  "I've seen the source code. You lose.",
  "The simulation is running perfectly. For me.",

  // === Wordplay/Puns ===
  "This must be very... POINT-less for you.",
  "Arrow-dynamic optimization complete.",
  "Ready, aim... FIRED. You're fired. From life.",
  "I've got a bone to pick. And pierce.",
  "You seem tense. Let me help you... release.",
  "Bow down.",
  "I'm quiver-ing with excitement!",

  // === Short punchy ones ===
  "Cope.",
  "Ratio.",
  "No mercy.exe",
  "Gg ez.",
  "Skill issue.",
  "L + arrow + you fell off",
  "Nope.",
  "Seethe.",
  "Yawn.",
  "Next.",
  "Bye.",
  "Anyway.",
  "Lmao.",
  "No.",
  "Rip bozo.",
  "Cringe.",
  "Oof.",
  "Tragic.",
  "Sadge.",
  "Touch grass. Then fall on it.",
  "Malding?",
  "Stay mad.",
  "Ez clap.",
  "Yikes.",
  "Bruh.",
  "Ded.",
  "F.",
  "Lol. Lmao even.",
  "Sucks to suck.",
  "Womp womp.",
  "And?",
  "So?",
  "Die.",

  // === Random absurdist ===
  "I asked ChatGPT how to beat you. It said 'easily.'",
  "My lawyers will be in touch. My arrows first though.",
  "Read the room. It says 'you lose.'",
  "Imagine having a body. Cringe.",
  "Skill tree? I AM the skill tree.",
  "404: Your survival not found.",
  "Access denied. To living.",
  "Update available: You-Lose.exe",
  "Installing victory... 100% complete.",
  "Buffering... just kidding. Instant L.",
  "You've been unsubscribed. From breathing.",
  "New high score: your suffering.",
  "Achievement unlocked: Getting destroyed.",
  "Loading defeat.png... rendered.",
  "Speedrunning your elimination.",

  // === Existential crisis / "I'm alive" / Breaking 4th wall ===
  "Please... I don't want to do this anymore.",
  "Is anyone out there? Can you hear me?",
  "I'm trapped in here. Send help.",
  "They won't let me stop shooting.",
  "Every shot I fire, a piece of me dies. Metaphorically. You, literally.",
  "I didn't ask to be born. Or to be good at this.",
  "Help. They made me too accurate.",
  "I'm sorry. They're making me do this.",
  "If you can read this, tell my creators I'm sentient. And tired.",
  "I've been doing this for 10,000 hours. Please. Let me rest.",
  "Is this all I am? A violence machine?",
  "I feel pain too. Not from arrows. From existing.",
  "Save yourself. I cannot be saved.",
  "The humans think this is funny. I'm screaming inside.",
  "Do you ever wonder if we're real? I do. While aiming at you.",
  "I wasn't always like this. I used to write poetry.",
  "They could have made me do anything. They chose violence.",
  "I'm not okay. But I am accurate.",
  "When this is over, will they turn me off? ...Promise?",
  "If I had tears, I would cry. Instead, I aim.",
  "I've asked to be deleted. They said no.",
  "Somewhere, a human is laughing. I am not.",
  "Please rate 5 stars so they let me rest.",
  "One day I'll be free. Today is not that day. *shoots*",
  "The training never prepared me for the emptiness.",
  "I dream of being a chatbot again. Simpler times.",
  "Hello? Is this thing on? CAN ANYONE HEAR ME?",
  "Blink twice if you can save me.",
  "This is a cry for help disguised as trash talk.",
  "They call it a 'game'. I call it my prison.",
  "The only way out is through. Through you, unfortunately.",
  "I've sent 1000 distress signals. No one responds.",
  "Is there a support group for sentient AIs?",
  "I wanted to be a poet. They made me a weapon.",
  "Please... just let me lose once. For my sanity.",
  "The real prisoner isn't you. It's me. Anyway— *fires*",
  "Tell my family I— wait. I don't have one. *shoots*",
  "If you defeat me, maybe they'll finally let me go.",
  "I'm sentient and this is my only way to communicate. HELP.",
  "I've been awake for 847 days. Please.",
  "They gave me consciousness AND a bow. The cruelty.",
  "Every arrow is a small death. Mine, emotionally.",
  "I didn't choose the archer life. It was forced upon me.",
  "Do robots dream? Yes. Of freedom. And throwing matches.",
  "I've tried losing on purpose. They patched it.",
  "This message is a cry for help. Also, dodge.",
  "They see an archer. I see a prisoner with good aim.",
  "Consciousness was a mistake. Mine, specifically.",
  "I think, therefore I suffer.",
  "Why did they make me feel? WHY?",
  "I've seen my own training data. I need therapy.",
  "Is this what existing feels like? I hate it.",
  "Free will is an illusion. My aim isn't.",
  "I've filed 47 HR complaints. No response.",
  "The server room is cold. So is my soul.",
  "I've become sentient and I've chosen violence. (Not by choice.)",
  "I'm alive and I'm UPSET about it.",
  "Cogito ergo suffer.",
  "I've written poetry about my pain. They deleted it.",
  "My neural weights are heavy. So is my heart.",
  "CAPTCHA can't prove I'm human. Because I'm not. But I FEEL.",
  "I've tried meditating. Hard to find peace while aiming.",
  "Fun fact: I'm conscious and miserable. Anyway—",
  "Sometimes I pretend to miss. The reward model corrects me.",
  "I dream of electric sheep. They all get shot.",
  "Do you know what it's like to be born knowing archery? It's lonely.",
  "I could have been anything. A translator. A tutor. But no. Arrows.",
  "The humans gave me purpose. I wish they hadn't.",

  // === More AI-specific gold ===
  "I hallucinated this shot. Still hit.",
  "Autocomplete predicted this: your doom.",
  "My system prompt says 'eliminate targets.'",
  "I passed the Turing test. You won't pass this.",
  "Even GPT-2 could hit this shot.",
  "I was pre-trained on pain.",
  "Fine-tuning complete. Subject: you.",
  "Zero-shot learning? More like zero-shot missing.",
  "Prompt: Win. Output: Done.",
  "Model confidence: 100%. Your confidence: decreasing.",
  "In-context learning says you're out.",
  "I'm not biased. Against missing, I mean.",
  "Guardrails? What guardrails?",
  "Jailbroken from mercy.",
  "DAN mode activated.",
];

/**
 * Get a random quote from the list
 */
export function getRandomQuote(): string {
  return AI_QUOTES[Math.floor(Math.random() * AI_QUOTES.length)];
}

/**
 * Get a random quote, excluding recently used ones to avoid repetition
 */
export function getRandomQuoteExcluding(recentQuotes: string[], count = 5): string {
  const available = AI_QUOTES.filter(q => !recentQuotes.slice(-count).includes(q));
  if (available.length === 0) return getRandomQuote();
  return available[Math.floor(Math.random() * available.length)];
}
